### ISSUE TITLE
E6.02 Update an item in catalogue of units

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#51] opened 2020-01-07 19:58 UTC
As the administrator, I update an item in catalogue of units, So
>>>administrator
>>>meal designer 
can use actual data about a unit 

>>>when he create or update an item of catalogue of meals or item of catalogue of products

**Comment by Joycelyn2015** [comment] 2020-05-01 20:33
Duplicate of issue #50: E7.02 Create/Update/Archive item in Catalog of Units

**Closed** 2020-05-01 20:33 UTC
Labels: user story
