### ISSUE TITLE
 E7.03 Archive an item in catalogue of products

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#56] opened 2020-01-07 23:13 UTC
As the administrator, I archive an item in catalogue of products, so client can not use the unit when he create or update an item of catalogue of meals.

**Comment by Joycelyn2015** [comment] 2020-05-01 21:04
Duplicate of issue #54: E7.01 Add/Update/Archive item in Catalogue of Products

**Closed by Joycelyn2015** 2020-05-01 21:04 UTC
Labels: user story
