### ISSUE TITLE
E7.03 Archive a product

### ISSUE THREAD

**Issue by professordro** [CivicTechFredericton/mealplanner#16] opened 2019-12-17 19:07 UTC
As an admin, I should be able to archive/delete a product, if it's no longer needed in any meals or becomes obsolete for some other reason

Archive status of a product should be reversible
A warning should be given if the product is still part of active meals

**Comment by Joycelyn2015** [comment] 2020-05-01 21:04
Duplicate of issue #54: E7.01 Add/Update/Archive item in Catalogue of Products

**Closed by Joycelyn2015** 2020-05-01 21:04 UTC
Labels: user story
