### ISSUE TITLE
[BUG] multiple tags are not getting created in Admin app product page

### ISSUE THREAD

**Issue by okayyjen** [CivicTechFredericton/mealplanner#483] opened 2023-08-23 16:54 UTC
**Describe the bug**
In the Admin app product page, when creating or editing a product, when the user goes to fill out the "tag" entry, if the user has more than 1 tag for a product, the correct number of tags are not created.

**To Reproduce**
1. Go to 'products/create'
2. Scroll down to 'tags' entry
3. Write more than 1 tag (i.e. grocery,vegan)
4. Click Save
5. See that only 1 tag is created for the product

**Expected behavior**
When the user wants a product to have more than 1 tag, they would enter into the tags field: "vegan,grocery". The tags for the product created should have 2 tags called "vegan" and "grocery".

**Screenshots**
example of how the tags should be getting created:
![image](https://github.com/CivicTechFredericton/mealplanner/assets/60271693/7eca81d2-1f61-4ea7-8720-0038c856a821)
example of how the tags are getting created incorrectly
![image](https://github.com/CivicTechFredericton/mealplanner/assets/60271693/eb037ca5-fd00-4c39-89b3-74ef1e90432a)

**Test Environment (please complete the following information):**
 - Any Browser [e.g. chrome, safari]

**Additional context**

**Comment by shanthisa** [comment] 2024-02-17 20:27
@ala-sk98 - Please test this test case and close this issue

**Comment by ala-sk98** [comment] 2024-02-22 22:48
> @ala-sk98 - Please test this test case and close this issue
The issue is tested:
Logged in to the Admin UI
Went to 'products/create'
Added more than 1 tag (i.e. grocery,vegan)
Clicked Save
Saw all tags are created for the product
![image](https://github.com/CivicTechFredericton/mealplanner/assets/59191427/b304755a-6baf-4ab6-8dd7-c400c43e15dd)

Ready to close.

**Comment by shanthisa** [comment] 2024-02-23 00:28
QA done. Closing the issue.

**Closed as completed by shanthisa** 2024-02-23 00:28 UTC
Labels: bug, admin UI - products

**Comment by ala-sk98** [comment] 2024-03-04 19:50
QA done.
Test case [AA-MultipleTags-016](https://github.com/CivicTechFredericton/mealplanner/wiki/Test-case-portfolio-v1.0-and-2.0/_edit#related-bug-bug-multiple-tags-are-not-getting-created-in-admin-app-product-page-483) : Passed.
