### ISSUE TITLE
5.1 Maintain Meal Catalogue

### ISSUE THREAD

**Issue by professordro** [CivicTechFredericton/mealplanner#43] opened 2020-01-06 17:05 UTC
Maintain Meal Instructions - maintain the detail in the Meal Plans
Stories in this epic mainly apply to the Green Village Meal Designer role.

**Comment by Joycelyn2015** [comment] 2020-05-01 21:57
Duplicate of issue #54: 7.5 I want to add/update/archive an item in catalog of meals

**Closed** 2020-05-01 21:58 UTC
Labels: Epic
