### ISSUE TITLE
E6.03 Archive an item in catalogue of units

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#52] opened 2020-01-07 20:00 UTC
As the administrator, I archive an item in catalogue of units, 
so I and  meal designer
can not use the unit 

>>>>when he create or update an item of catalogue of meals or item of catalogue of products.

**Comment by Joycelyn2015** [comment] 2020-05-01 20:40
Duplicate of issue #50: E7.02 Create/Update/Archive item in Catalog of Units

**Closed by Joycelyn2015** 2020-05-01 20:40 UTC
Labels: user story
