### ISSUE TITLE
E7.04 Search for a product

### ISSUE THREAD

**Issue by professordro** [CivicTechFredericton/mealplanner#17] opened 2019-12-17 19:16 UTC
As an admin, I should be able to search for a product, in order to find it quickly for update

When maintaining the catalogue of products, I should be able to search by text or keyword to find the product I wish to update or archive

**Comment by Joycelyn2015** [comment] 2020-05-01 21:17
Duplicate of issue #50

**Closed** 2020-05-01 21:18 UTC
Labels: user story
