### ISSUE TITLE
 E7.02 Update an item in catalogue of products

### ISSUE THREAD

**Issue by ElvinaCherepovich** [CivicTechFredericton/mealplanner#55] opened 2020-01-07 23:10 UTC
As the administrator, I update an item in catalogue of products, 
so administrator can use actual data about a unit when he create or update an item of catalogue of meals

**Comment by Joycelyn2015** [comment] 2020-05-01 21:03
Duplicate of issue #54: E7.01 Add/Update/Archive item in Catalogue of Products

**Closed by Joycelyn2015** 2020-05-01 21:03 UTC
Labels: user story
